#!/bin/sh
set -e

case "$1" in
    remove)
	systemctl disable graylog-web.service || true
    ;;

    purge)
        rm -rf /var/lib/graylog-web /var/log/graylog-web

        deluser graylog-web || true
        delgroup graylog-web || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
