#!/bin/sh
set -e

case "$1" in
    remove)
        # Nothing to do here
    ;;

    purge)
        rm -rf /var/lib/graylog2-server /var/log/graylog2-server
        rm -f /etc/graylog2/server/node-id

        deluser graylog2 || true
        delgroup graylog2 || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
