#!/bin/sh
set -e

case "$1" in
    remove)
        # Nothing to do here
    ;;

    purge)
        rm -rf /var/lib/graylog2-radio /var/log/graylog2-radio
        rm -f /etc/graylog2/radio/node-id

        deluser graylog2-radio || true
        delgroup graylog2-radio || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
