#!/bin/sh
set -e

case "$1" in
    remove)
        update-rc.d graylog-server remove >/dev/null || true
    ;;

    purge)
        rm -rf /var/lib/graylog-server /var/log/graylog-server
        rm -f /etc/graylog/server/node-id

        deluser graylog || true
        delgroup graylog || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
