#!/bin/sh

set -e

# Flag to indicate if this is an upgrade
upgrade="false"

case "$1" in
	# DEB based systems
	configure)
		if [ -z "$2" ]; then
			upgrade="false"
		else
			upgrade="true"
		fi
		;;
	abort-deconfigure|abort-upgrade|abort-remove)
		;;
	# RPM based systems
	1)
		# Installation
		upgrade="false"
		;;
	2)
		# Upgrade
		upgrade="true"
		;;
	*)
		echo "[ERROR] post-install script called with unknown argument: '$1'"
		exit 1
		;;
esac

chmod 0644 /etc/graylog/illuminate/core/*
chmod 0644 /etc/graylog/illuminate/windows/*
chmod 0644 /etc/graylog/illuminate/okta/*
chmod 0644 /etc/graylog/illuminate/paloalto/*
chmod 0644 /etc/graylog/illuminate/o365/*
chmod 0644 /usr/share/graylog-illuminate/content_packs/illuminate_core/*
chmod 0644 /usr/share/graylog-illuminate/content_packs/illuminate_events/*
chmod 0644 /usr/share/graylog-illuminate/content_packs/illuminate_o365/*
chmod 0644 /usr/share/graylog-illuminate/content_packs/illuminate_okta/*
chmod 0644 /usr/share/graylog-illuminate/content_packs/illuminate_paloalto/*
chmod 0644 /usr/share/graylog-illuminate/content_packs/illuminate_windows/*

if [ ! -f "/etc/graylog/illuminate/core/static_accounts.csv" ]; then
	cp /etc/graylog/illuminate/core/static_accounts.csv.default /etc/graylog/illuminate/core/static_accounts.csv
fi

if [ ! -f "/etc/graylog/illuminate/core/static_devices.csv" ]; then
	cp /etc/graylog/illuminate/core/static_devices.csv.default /etc/graylog/illuminate/core/static_devices.csv
fi

if [ "$upgrade" = "true" ]; then
	# This is an upgrade, exit early.
	exit 0
fi


exit 0
