#!/bin/sh
set -e

case "$1" in
    configure)
	user="graylog2-radio"
	group="graylog2-radio"
	datadir="/var/lib/graylog2-radio"
	logdir="/var/log/graylog2-radio"
	radio_node_id="/etc/graylog2/radio/node-id"

	if ! getent group "$group" > /dev/null 2>&1 ; then
	    addgroup --system "$group" --quiet
	fi

	if ! id "$user" > /dev/null 2>&1 ; then
	    adduser --system --home "$datadir" --no-create-home \
		--ingroup "$group" --disabled-password \
		--shell /bin/false "$user"
	fi

	install -d -o "$user" -g "$group" -m 0755 "$datadir"
	install -d -o "$user" -g "$group" -m 0755 "$logdir"

	# Create an initial radio node-id.
	if [ ! -s "$radio_node_id" ]; then
		uuidgen > "$radio_node_id"
	fi
    ;;
esac
