# Avoid triggering needrestart(1) for library files in the Graylog data
# directory. Graylog writes native libraries to that directory at runtime.
push @{$nrconf{blacklist_mappings}}, qr(^/var/lib/graylog-server/);
