#!/bin/sh

set -e

user="graylog"
group="graylog"
datadir="/var/lib/graylog-server"
logdir="/var/log/graylog-server"

remove_data="false"

case "$1" in
	# DEB based systems
	remove)
		remove_data="false"
		;;

	purge)
		remove_data="true"
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		# Nothing to do here
		;;
	# RPM based systems
	0)
		# Removal
		remove_data="true"
		;;
	1)
		# Upgrade
		remove_data="false"
		;;
	*)
		echo "[ERROR] post-uninstall script called with unknown argument: '$1'"
		exit 1
		;;
esac

if [ "$remove_data" = "true" ]; then
	rm -rf "$datadir" "$logdir"
	rm -f /etc/graylog/server/node-id
	rm -f /etc/init/graylog-server.override

	if id "$user" > /dev/null 2>&1 ; then
		userdel "$user" || true
	fi

	if getent group "$group" > /dev/null 2>&1 ; then
		groupdel "$group" || true
	fi
fi

exit 0
