#!/bin/sh

set -e

stopping="false"

case "$1" in
	# DEB based systems
	remove)
		stopping="true"
		;;
	upgrade)
		stopping="false"
		;;
	deconfigure|failed-upgrade)
		;;
	# RPM based systems
	0)
		# Removal
		stopping="true"
		;;
	1)
		# Upgrade
		stopping="false"
		;;
	*)
		echo "[ERROR] pre-uninstall script called with unknown argument: '$1'"
		exit 1
		;;
esac

if [ "$stopping" = "false" ]; then
	# Nothing to stop, exit early.
	exit 0
fi

# Order is important! Some systems might have both commands!
if command -v systemctl >/dev/null; then
	systemctl --no-reload stop graylog-server.service >/dev/null 2>&1 || true
	systemctl disable graylog-server>/dev/null 2>&1 || true
elif command -v chkconfig >/dev/null; then
	/etc/init.d/graylog-server stop || true
	chkconfig --del graylog-server 2>/dev/null || true
elif command -v initctl >/dev/null; then
	stop graylog-server 2>/dev/null || true
	echo "manual" > "/etc/init/graylog-server.override" || true
elif command -v update-rc.d >/dev/null; then
	/etc/init.d/graylog-server stop || true
        update-rc.d graylog-server remove >/dev/null || true
fi

exit 0
