#!/bin/sh
set -e

case "$1" in
    configure)
	user="graylog-collector"
	group="graylog-collector"
	datadir="/var/lib/graylog-collector"
	logdir="/var/log/graylog-collector"
	collector_node_id="/etc/graylog/collector/collector-id"

	if ! getent group "$group" > /dev/null 2>&1 ; then
	    addgroup --system "$group" --quiet
	fi

	install -d -o "root" -g "root" -m 0755 "$datadir"

	if ! id "$user" > /dev/null 2>&1 ; then
	    adduser --system --home "$datadir" --no-create-home \
		--ingroup "$group" --disabled-password \
		--shell /bin/false "$user"
	fi

	chown -R "$user":"$group" "$datadir"
	install -d -o "$user" -g "$group" -m 0755 "$logdir"

	# Create an initial collector-id.
	if [ ! -s "$collector_node_id" ]; then
		uuidgen > "$collector_node_id"
	fi

	# Enable service
	systemctl enable graylog-collector.service
    ;;
esac
