#!/bin/sh
set -e

case "$1" in
    remove)
	systemctl disable graylog-collector.service || true
    ;;

    purge)
        rm -rf /var/lib/graylog-collector /var/log/graylog-collector
        rm -f /etc/graylog/collector/collector-id

        deluser graylog-collector || true
        delgroup graylog-collector || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
