#!/bin/sh
set -e

case "$1" in
    remove)
        update-rc.d graylog-radio remove >/dev/null || true
    ;;

    purge)
        rm -rf /var/lib/graylog-radio /var/log/graylog-radio
        rm -f /etc/graylog/radio/node-id

        deluser graylog-radio || true
        delgroup graylog-radio || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
