#!/bin/sh
set -e

case "$1" in
    configure)
	user="graylog-radio"
	group="graylog-radio"
	datadir="/var/lib/graylog-radio"
	logdir="/var/log/graylog-radio"
	radio_node_id="/etc/graylog/radio/node-id"

	if ! getent group "$group" > /dev/null 2>&1 ; then
	    addgroup --system "$group" --quiet
	fi

	install -d -o "root" -g "root" -m 0755 "$datadir"

	if ! id "$user" > /dev/null 2>&1 ; then
	    adduser --system --home "$datadir" --no-create-home \
		--ingroup "$group" --disabled-password \
		--shell /bin/false "$user"
	fi

	chown -R "$user":"$group" "$datadir"
	install -d -o "$user" -g "$group" -m 0755 "$logdir"

	# Create an initial radio node-id.
	if [ ! -s "$radio_node_id" ]; then
		uuidgen > "$radio_node_id"
	fi

	update-rc.d graylog-radio defaults 95 10 >/dev/null
    ;;
esac
