name: "Build Container Images"

on:
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        image:
          - "ubuntu2004"
          - "alma9"

    permissions:
      contents: "read"
      packages: "write"
      id-token: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"

      - name: "Login to container registry"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "Graylog2"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build and push image - ${{ matrix.image }}"
        uses: "docker/build-push-action@v6"
        with:
          context: "docker/${{ matrix.image }}"
          push: true
          tags: "ghcr.io/graylog2/fpm-recipes-builder-${{ matrix.image }}:latest"
